#############################################
#                  Wilovy09                 #
#                                           #
#-----------------Animation-----------------#
animations = true;
animation-stiffness-in-tag = 125;
animation-stiffness-tag-change = 90.0;
animation-window-mass = 0.4;
animation-dampening = 15;
animation-clamping = true;
animation-for-open-window = "zoom";
animation-for-unmap-window = "squeeze";
animation-for-transient-window = "slide-up";
animation-for-prev-tag = "minimize";
enable-fading-prev-tag = true;
animation-for-next-tag = "slide-in-center";
enable-fading-next-tag = true;
#--------------------Fade-------------------#
fading = true;
fade-in-step = 0.023;
fade-out-step = 0.035;
fade-delta = 10;
#-------------------Corners-----------------#
corner-radius = 10;
round-borders = 5;
rounded-corners-exclude = [
  "class_g ?= 'Polybar'",
];
#-----------Background-Blurring-------------#
blur: {
  method = "dual_kawase";
  strength = 3;
  background = true;
  background-frame = false;
  background-fixed = false;
}
blur-background-exclude = [
	"class_g ?= 'polybar'",
  "class_g ?= 'deepin-screen-recorder'"
];
#---------Transparency / Opacity------------#
inactive-opacity = 0.9;
inactive-dim-fixed = true;
focus-exclude = [
  "class_g ?= 'polybar'",
  "class_g ?= 'rofi'",
];
opacity-rule = [
	"95:class_g = 'Code' && focused",
];

backend = "glx";
vsync = true;
glx-no-stencil = true;
log-level = "info";