[language-server.tailwindcss-ls]
config = { userLanguages = { vue = "html", "*.vue" = "html", astro = "html", "*.astro" = "html", "edge" = "html", "*.edge" = "html" } }

[[language]]
name = "vue"
auto-format = true
language-servers = ["tailwindcss-ls", "vue-language-server", "emmet-lsp", "typescript-language-server", "vscode-html-language-server", "vscode-css-language-server"]
formatter = { command = 'prettier', args = ["--parser", "vue"] }

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/home/wilovy/.local/share/fnm/node-versions/v20.15.0/installation/lib/node_modules/@vue/language-server/"
languages = ["vue"]

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "/home/wilovy/.local/share/fnm/node-versions/v20.15.0/installation/lib/node_modules/typescript/lib/"}, environment = "node"}

[[language]]
name = "astro"
auto-format = true
language-servers = [ "emmet-lsp", "tailwindcss-ls", "astro-ls", "typescript-language-server", "css-language-server"]
formatter = { command = 'prettier', args = ["--parser", "astro"] }
# -------
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = [".git"]
file-types = ["html", "edge"]
language-servers = ["emmet-lsp", "vscode-html-language-server"]

[languages.typescript]
language-server = [
  { command = "typescript-language-server", args = "--stdio" }
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[languages.javascript]
language-server = { command = "typescript-language-server", args = "--stdio" }

[[language]]
name = "jsx"
language-servers = [ "emmet-lsp", "typescript-language-server", "vscode-css-language-server" ]

[[language]]
name = "tsx"
language-servers = [ "emmet-lsp", "typescript-language-server", "vscode-css-language-server", "vscode-html-language-server" ]

[languages.json]
language-server = { command = "json-languageserver", args = ["--stdio"] }

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server"]

[languages.go]
language-server = { command = "gopls" }

[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

[language-server.gpt]
command = "helix-gpt"

# [[language]]
# name = "edge"
# file-types = ["edge"]
# scope = ""
# auto-format = true
# language-servers = [ "emmet-lsp", "tailwindcss-ls", "typescript-language-server", "vscode-html-language-server", "css-language-server"]
# formatter = { command = 'prettier', args = ["--parser", "html"] }
# grammar = "edge"

# [[grammar]]
# name = "edge"
# source = { git = "https://github.com/duyluonglc/edge-sublime-syntax", rev = "e7bf01cf48d5b83bb9666a03726b62c29d716d13" }
