#!/usr/bin/env bash

feh --bg-scale ~/wilovy.nix/Backgrounds/woman_gruvbox_activate.jpg
picom &
deadd-notification-center &

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
# ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# eww daemon -c $HOME/.config/eww &

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"
